# Generated by Django 5.1.6 on 2025-04-24 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="stars",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "Avaliação deve ser superior a 0 estrelas."
                    ),
                    django.core.validators.MaxValueValidator(
                        5, "Avaliação deve ser inferior a 6 estrelas."
                    ),
                ]
            ),
        ),
    ]
